version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - mynetwork
    volumes:
      - ./app:/app
      - ./.env:/app/.env

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
