version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ./app:/app

networks:
  mynetwork:
    driver: bridge
